curl -XPOST http://localhost:8003/data/reqs -d '{"name":"reqs","desc":"request data"}' -H"Content-Type: application/json"
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"30"}' -H"Content-Type: application/json"                      
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"20"}' -H"Content-Type: application/json"
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"26"}' -H"Content-Type: application/json"
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"20"}' -H"Content-Type: application/json"
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"19"}' -H"Content-Type: application/json"
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"24"}' -H"Content-Type: application/json"
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"16"}' -H"Content-Type: application/json"
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"19"}' -H"Content-Type: application/json"
curl -XPUT http://localhost:8003/data/reqs -d '{"avg":"32"}' -H"Content-Type: application/json"
